# Generated by Django 4.1 on 2024-04-29 16:50

from django.db import migrations, models
import executives.models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0002_alter_executive_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='resume',
            field=models.FileField(upload_to='resumes/', validators=[executives.models.validate_pdf_extension]),
        ),
    ]
