# Generated by Django 4.1 on 2024-04-26 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.executive')),
            ],
        ),
        migrations.CreateModel(
            name='PositionConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('protocol_number', models.CharField(max_length=100)),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.executive')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('graduation_year', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.executive')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.executive')),
            ],
        ),
    ]
