# Generated by Django 4.1 on 2024-04-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_workexperience_positionconsent_education_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='executive',
        ),
        migrations.RemoveField(
            model_name='executive',
            name='user',
        ),
        migrations.RemoveField(
            model_name='positionconsent',
            name='executive',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='executive',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Executive',
        ),
        migrations.DeleteModel(
            name='PositionConsent',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
